### ISSUE TITLE
Support sub-folder of a git repo to indicate the hcl location

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/terraform-controller#124]
Currently, we have supported a remote git repo to indicate the location of HCL files https://github.com/oam-dev/terraform-controller/blob/master/examples/alibaba/eip/configuration_eip_remote.yaml#L6.

```
apiVersion: terraform.core.oam.dev/v1beta1
kind: Configuration
metadata:
  name: alibaba-eip-remote
spec:
  remote: https://github.com/zzxwill/terraform-alibaba-eip.git

  variable:
    name: poc
    bandwidth: 1
```

There are voices from the community: We need a repo with several sub-folder to store HCL files for different cloud resources respectively.

```
https://github.com/oam-dev/terraform-controller/tree/master/examples/tf-native/alibaba/eip: Alibaba Cloud EIP HCLs
https://github.com/oam-dev/terraform-controller/tree/master/examples/tf-native/aws/hcl: AWS S3 HCLs
```
