### ISSUE TITLE
Invalid region error is not clear

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/terraform-controller#190]
```
  services:
  - healthy: false
    message: "\e[31m│\e[0m \e[0m\e[1m\e[31mError: \e[0m\e[0m\e[1mInvalid provider
      configuration\e[0m"
    name: poc
    workloadDefinition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
  status: unhealthy
```

```
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
╷
│ Error: Invalid provider configuration
│
│ Provider "registry.terraform.io/hashicorp/alicloud" requires explicit
│ configuration. Add a provider block to the root module and configure the
│ provider's required arguments as described in the provider documentation.
│
╵
╷
│ Error: Invalid Alibaba Cloud region: us-west-xxx
│
│   with provider["registry.terraform.io/hashicorp/alicloud"],
│   on <empty> line 0:
│   (source code not available)
│
```
