### ISSUE TITLE
Two configurations with same names and different namespaces won't all get provisioned successfully 

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/terraform-controller#192]
Reported by a friend from Youzan Ltd.

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: wwtest
spec:
  components:
    - name: wwtest
      type: ucloud-redis
      properties:
        name: wwtest
        vpc_id: XXXXXX
        subnet_id:  XXXXX
        charge_type: dynamic
        deleteResource: false
        writeConnectionSecretToRef:
          name: wwtest-conn

```
