### ISSUE TITLE
Failed to parse complicated outputs

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/terraform-controller#274]
When Terraform State JSON is below, it could not be parsed.
```
{
  "version": 4,
  "terraform_version": "1.0.2",
  "serial": 1,
  "lineage": "144ace19-2a0b-c070-f9a7-7138b858d056",
  "outputs": {
    "additional_cluster_endpoints": {
      "value": {},
      "type": [
        "object",
        {}
      ]
    },
    "cluster_arn": {
      "value": "arn:aws:rds:us-east-1:753387532736:cluster:test-rds",
      "type": "string"
    },
    "cluster_database_name": {
      "value": "defaultdb",
      "type": "string"
    },
    "cluster_endpoint": {
      "value": "test-rds.cluster-cxwwadngf1nh.us-east-1.rds.amazonaws.com",
      "type": "string"
    },
    "cluster_engine_version_actual": {
      "value": "11.9",
      "type": "string"
    },
    "cluster_hosted_zone_id": {
      "value": "Z2R2ITUGPM61AM",
      "type": "string"
    },
    "cluster_id": {
      "value": "test-rds",
      "type": "string"
    },
    "cluster_instances": {
      "value": {
        "one": {
          "apply_immediately": true,
          "arn": "arn:aws:rds:us-east-1:753387532736:db:test-rds-one",
          "auto_minor_version_upgrade": true,
          "availability_zone": "us-east-1d",
          "ca_cert_identifier": "rds-ca-2019",
          "cluster_identifier": "test-rds",
          "copy_tags_to_snapshot": false,
          "db_parameter_group_name": "default.aurora-postgresql11",
          "db_subnet_group_name": "default",
          "dbi_resource_id": "db-VNTPOSYC7EJY5ZB43CACR64MZE",
          "endpoint": "test-rds-one.cxwwadngf1nh.us-east-1.rds.amazonaws.com",
          "engine": "aurora-postgresql",
          "engine_version": "11.9",
          "engine_version_actual": "11.9",
          "id": "test-rds-one",
          "identifier": "test-rds-one",
          "identifier_prefix": null,
          "instance_class": "db.r5.large",
          "kms_key_id": "arn:aws:kms:us-east-1:753387532736:key/25c6f967-c093-4875-af28-9fdfe4f7d77a",
          "monitoring_interval": 0,
          "monitoring_role_arn": "",
          "performance_insights_enabled": false,
          "performance_insights_kms_key_id": "",
          "performance_insights_retention_period": 0,
          "port": 5432,
          "preferred_backup_window": "02:00-03:00",
          "preferred_maintenance_window": "sun:05:00-sun:06:00",
          "promotion_tier": 0,
          "publicly_accessible": false,
          "storage_encrypted": true,
          "tags": null,
          "tags_all": {},
          "timeouts": {
            "create": null,
            "delete": null,
            "update": null
          },
          "writer": true
        }
      },
      "type": [
        "object",
        {
          "one": [
            "object",
            {
              "apply_immediately": "bool",
              "arn": "string",
              "auto_minor_version_upgrade": "bool",
              "availability_zone": "string",
              "ca_cert_identifier": "string",
              "cluster_identifier": "string",
              "copy_tags_to_snapshot": "bool",
              "db_parameter_group_name": "string",
              "db_subnet_group_name": "string",
              "dbi_resource_id": "string",
              "endpoint": "string",
              "engine": "string",
              "engine_version": "string",
              "engine_version_actual": "string",
              "id": "string",
              "identifier": "string",
              "identifier_prefix": "string",
              "instance_class": "string",
              "kms_key_id": "string",
              "monitoring_interval": "number",
              "monitoring_role_arn": "string",
              "performance_insights_enabled": "bool",
              "performance_insights_kms_key_id": "string",
              "performance_insights_retention_period": "number",
              "port": "number",
              "preferred_backup_window": "string",
              "preferred_maintenance_window": "string",
              "promotion_tier": "number",
              "publicly_accessible": "bool",
              "storage_encrypted": "bool",
              "tags": [
                "map",
                "string"
              ],
              "tags_all": [
                "map",
                "string"
              ],
              "timeouts": [
                "object",
                {
                  "create": "string",
                  "delete": "string",
                  "update": "string"
                }
              ],
              "writer": "bool"
            }
          ]
        }
      ]
    },
    "cluster_master_password": {
      "value": "defaultpassword",
      "type": "string",
      "sensitive": true
    },
    "cluster_master_username": {
      "value": "defaultuser",
      "type": "string",
      "sensitive": true
    },
    "cluster_members": {
      "value": [],
      "type": [
        "set",
        "string"
      ]
    },
    "cluster_port": {
      "value": 5432,
      "type": "number"
    },
    "cluster_reader_endpoint": {
      "value": "test-rds.cluster-ro-cxwwadngf1nh.us-east-1.rds.amazonaws.com",
      "type": "string"
    },
    "cluster_resource_id": {
      "value": "cluster-U4CIU3REOT5JNHM6P7OKQSZFWE",
      "type": "string"
    },
    "cluster_role_associations": {
      "value": {},
      "type": [
        "object",
        {}
      ]
    },
    "db_subnet_group_name": {
      "value": "",
      "type": "string"
    },
    "enhanced_monitoring_iam_role_arn": {
      "value": "",
      "type": "string"
    },
    "enhanced_monitoring_iam_role_name": {
      "value": "",
      "type": "string"
    },
    "enhanced_monitoring_iam_role_unique_id": {
      "value": "",
      "type": "string"
    },
    "security_group_id": {
      "value": "",
      "type": "string"
    }
  },
  "resources": [
    {
      "mode": "data",
      "type": "aws_iam_policy_document",
      "name": "monitoring_rds_assume_role",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "1813475199",
            "json": "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\": \"\",\n      \"Effect\": \"Allow\",\n      \"Action\": \"sts:AssumeRole\",\n      \"Principal\": {\n        \"Service\": \"monitoring.rds.amazonaws.com\"\n      }\n    }\n  ]\n}",
            "override_json": null,
            "override_policy_documents": null,
            "policy_id": null,
            "source_json": null,
            "source_policy_documents": null,
            "statement": [
              {
                "actions": [
                  "sts:AssumeRole"
                ],
                "condition": [],
                "effect": "Allow",
                "not_actions": [],
                "not_principals": [],
                "not_resources": [],
                "principals": [
                  {
                    "identifiers": [
                      "monitoring.rds.amazonaws.com"
                    ],
                    "type": "Service"
                  }
                ],
                "resources": [],
                "sid": ""
              }
            ],
            "version": "2012-10-17"
          },
          "sensitive_attributes": []
        }
      ]
    },
    {
      "mode": "data",
      "type": "aws_partition",
      "name": "current",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "dns_suffix": "amazonaws.com",
            "id": "aws",
            "partition": "aws",
            "reverse_dns_prefix": "com.amazonaws"
          },
          "sensitive_attributes": []
        }
      ]
    },
    {
      "mode": "managed",
      "type": "aws_rds_cluster",
      "name": "this",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "index_key": 0,
          "schema_version": 0,
          "attributes": {
            "allow_major_version_upgrade": false,
            "apply_immediately": true,
            "arn": "arn:aws:rds:us-east-1:753387532736:cluster:test-rds",
            "availability_zones": [
              "us-east-1a",
              "us-east-1c",
              "us-east-1d"
            ],
            "backtrack_window": 0,
            "backup_retention_period": 7,
            "cluster_identifier": "test-rds",
            "cluster_identifier_prefix": null,
            "cluster_members": [],
            "cluster_resource_id": "cluster-U4CIU3REOT5JNHM6P7OKQSZFWE",
            "copy_tags_to_snapshot": false,
            "database_name": "defaultdb",
            "db_cluster_parameter_group_name": "default.aurora-postgresql11",
            "db_instance_parameter_group_name": null,
            "db_subnet_group_name": "default",
            "deletion_protection": false,
            "enable_global_write_forwarding": false,
            "enable_http_endpoint": false,
            "enabled_cloudwatch_logs_exports": null,
            "endpoint": "test-rds.cluster-cxwwadngf1nh.us-east-1.rds.amazonaws.com",
            "engine": "aurora-postgresql",
            "engine_mode": "provisioned",
            "engine_version": "11.9",
            "engine_version_actual": "11.9",
            "final_snapshot_identifier": "final-test-rds-d9b751c6",
            "global_cluster_identifier": "",
            "hosted_zone_id": "Z2R2ITUGPM61AM",
            "iam_database_authentication_enabled": false,
            "iam_roles": [],
            "id": "test-rds",
            "kms_key_id": "arn:aws:kms:us-east-1:753387532736:key/25c6f967-c093-4875-af28-9fdfe4f7d77a",
            "master_password": "defaultpassword",
            "master_username": "defaultuser",
            "port": 5432,
            "preferred_backup_window": "02:00-03:00",
            "preferred_maintenance_window": "sun:05:00-sun:06:00",
            "reader_endpoint": "test-rds.cluster-ro-cxwwadngf1nh.us-east-1.rds.amazonaws.com",
            "replication_source_identifier": "",
            "restore_to_point_in_time": [],
            "s3_import": [],
            "scaling_configuration": [],
            "skip_final_snapshot": false,
            "snapshot_identifier": null,
            "source_region": null,
            "storage_encrypted": true,
            "tags": null,
            "tags_all": {},
            "timeouts": {
              "create": null,
              "delete": null,
              "update": null
            },
            "vpc_security_group_ids": [
              "sg-6316a612"
            ]
          },
          "sensitive_attributes": [],
          "private": "eyJlMmJmYjczMC1lY2FhLTExZTYtOGY4OC0zNDM2M2JjN2M0YzAiOnsiY3JlYXRlIjo3MjAwMDAwMDAwMDAwLCJkZWxldGUiOjcyMDAwMDAwMDAwMDAsInVwZGF0ZSI6NzIwMDAwMDAwMDAwMH19",
          "dependencies": [
            "aws_db_subnet_group.this",
            "aws_security_group.this",
            "random_id.snapshot_identifier",
            "random_password.master_password"
          ]
        }
      ]
    },
    {
      "mode": "managed",
      "type": "aws_rds_cluster_instance",
      "name": "this",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "index_key": "one",
          "schema_version": 0,
          "attributes": {
            "apply_immediately": true,
            "arn": "arn:aws:rds:us-east-1:753387532736:db:test-rds-one",
            "auto_minor_version_upgrade": true,
            "availability_zone": "us-east-1d",
            "ca_cert_identifier": "rds-ca-2019",
            "cluster_identifier": "test-rds",
            "copy_tags_to_snapshot": false,
            "db_parameter_group_name": "default.aurora-postgresql11",
            "db_subnet_group_name": "default",
            "dbi_resource_id": "db-VNTPOSYC7EJY5ZB43CACR64MZE",
            "endpoint": "test-rds-one.cxwwadngf1nh.us-east-1.rds.amazonaws.com",
            "engine": "aurora-postgresql",
            "engine_version": "11.9",
            "engine_version_actual": "11.9",
            "id": "test-rds-one",
            "identifier": "test-rds-one",
            "identifier_prefix": null,
            "instance_class": "db.r5.large",
            "kms_key_id": "arn:aws:kms:us-east-1:753387532736:key/25c6f967-c093-4875-af28-9fdfe4f7d77a",
            "monitoring_interval": 0,
            "monitoring_role_arn": "",
            "performance_insights_enabled": false,
            "performance_insights_kms_key_id": "",
            "performance_insights_retention_period": 0,
            "port": 5432,
            "preferred_backup_window": "02:00-03:00",
            "preferred_maintenance_window": "sun:05:00-sun:06:00",
            "promotion_tier": 0,
            "publicly_accessible": false,
            "storage_encrypted": true,
            "tags": null,
            "tags_all": {},
            "timeouts": {
              "create": null,
              "delete": null,
              "update": null
            },
            "writer": true
          },
          "sensitive_attributes": [],
          "private": "eyJlMmJmYjczMC1lY2FhLTExZTYtOGY4OC0zNDM2M2JjN2M0YzAiOnsiY3JlYXRlIjo1NDAwMDAwMDAwMDAwLCJkZWxldGUiOjU0MDAwMDAwMDAwMDAsInVwZGF0ZSI6NTQwMDAwMDAwMDAwMH19",
          "dependencies": [
            "aws_db_subnet_group.this",
            "aws_iam_role.rds_enhanced_monitoring",
            "aws_rds_cluster.this",
            "aws_security_group.this",
            "random_id.snapshot_identifier",
            "random_password.master_password"
          ]
        }
      ]
    },
    {
      "mode": "managed",
      "type": "random_id",
      "name": "snapshot_identifier",
      "provider": "provider[\"registry.terraform.io/hashicorp/random\"]",
      "instances": [
        {
          "index_key": 0,
          "schema_version": 0,
          "attributes": {
            "b64_std": "2bdRxg==",
            "b64_url": "2bdRxg",
            "byte_length": 4,
            "dec": "3652669894",
            "hex": "d9b751c6",
            "id": "2bdRxg",
            "keepers": {
              "id": "test-rds"
            },
            "prefix": null
          },
          "sensitive_attributes": [],
          "private": "bnVsbA=="
        }
      ]
    }
  ]
}

```

The error message is below.
```
status:
  apply:
    message: 'Hit an issue to generate outputs: json: cannot unmarshal array into
      Go struct field TfStateProperty.outputs.type of type string'
    state: GeneratingTerraformOutputs
  destroy: {}
```

**Comment by zzxwill** [comment]
Here are two drawbacks of exposing type in outputs.
it’s in Terraform context, not friendly to Golang/Kubernetes
it’s complicated. It's so annoying like you saide, for example, I was terrified by the type of cluster_instances .

Proposed to remove `type` from .status.apply.outputs.

```
    outputs:
      additional_cluster_endpoints:
        type: '["object",{}]'
        value: '{}'
      cluster_arn:
        type: string
        value: arn:aws:rds:us-east-1:753387532736:cluster:test-rds
      cluster_database_name:
        type: string
        value: defaultdb
      cluster_endpoint:
        type: string
        value: test-rds.cluster-cxwwadngf1nh.us-east-1.rds.amazonaws.com
      cluster_engine_version_actual:
        type: string
        value: "11.9"
      cluster_hosted_zone_id:
        type: string
        value: Z2R2ITUGPM61AM
      cluster_id:
        type: string
        value: test-rds
      cluster_instances:
        type: '["object",{"one":["object",{"apply_immediately":"bool","arn":"string","auto_minor_version_upgrade":"bool","availability_zone":"string","ca_cert_identifier":"string","cluster_identifier":"string","copy_tags_to_snapshot":"bool","db_parameter_group_name":"string","db_subnet_group_name":"string","dbi_resource_id":"string","endpoint":"string","engine":"string","engine_version":"string","engine_version_actual":"string","id":"string","identifier":"string","identifier_prefix":"string","instance_class":"string","kms_key_id":"string","monitoring_interval":"number","monitoring_role_arn":"string","performance_insights_enabled":"bool","performance_insights_kms_key_id":"string","performance_insights_retention_period":"number","port":"number","preferred_backup_window":"string","preferred_maintenance_window":"string","promotion_tier":"number","publicly_accessible":"bool","storage_encrypted":"bool","tags":["map","string"],"tags_all":["map","string"],"timeouts":["object",{"create":"string","delete":"string","update":"string"}],"writer":"bool"}]}]'
        value: '{"one":{"apply_immediately":true,"arn":"arn:aws:rds:us-east-1:753387532736:db:test-rds-one","auto_minor_version_upgrade":true,"availability_zone":"us-east-1d","ca_cert_identifier":"rds-ca-2019","cluster_identifier":"test-rds","copy_tags_to_snapshot":false,"db_parameter_group_name":"default.aurora-postgresql11","db_subnet_group_name":"default","dbi_resource_id":"db-VNTPOSYC7EJY5ZB43CACR64MZE","endpoint":"test-rds-one.cxwwadngf1nh.us-east-1.rds.amazonaws.com","engine":"aurora-postgresql","engine_version":"11.9","engine_version_actual":"11.9","id":"test-rds-one","identifier":"test-rds-one","identifier_prefix":null,"instance_class":"db.r5.large","kms_key_id":"arn:aws:kms:us-east-1:753387532736:key/25c6f967-c093-4875-af28-9fdfe4f7d77a","monitoring_interval":0,"monitoring_role_arn":"","performance_insights_enabled":false,"performance_insights_kms_key_id":"","performance_insights_retention_period":0,"port":5432,"preferred_backup_window":"02:00-03:00","preferred_maintenance_window":"sun:05:00-sun:06:00","promotion_tier":0,"publicly_accessible":false,"storage_encrypted":true,"tags":null,"tags_all":{},"timeouts":{"create":null,"delete":null,"update":null},"writer":true}}'
      cluster_master_password:
        type: string
        value: defaultpassword
      cluster_master_username:
        type: string
        value: defaultuser
      cluster_members:
        type: '["set","string"]'
        value: '[]'
      cluster_port:
        type: number
        value: "5432"
      cluster_reader_endpoint:
        type: string
        value: test-rds.cluster-ro-cxwwadngf1nh.us-east-1.rds.amazonaws.com
      cluster_resource_id:
        type: string
        value: cluster-U4CIU3REOT5JNHM6P7OKQSZFWE
      cluster_role_associations:
        type: '["object",{}]'
        value: '{}'
      db_subnet_group_name:
        type: string
      enhanced_monitoring_iam_role_arn:
        type: string
      enhanced_monitoring_iam_role_name:
        type: string
      enhanced_monitoring_iam_role_unique_id:
        type: string
      security_group_id:
        type: string
```
