### ISSUE TITLE
helm template error

### ISSUE THREAD

**Issue by wanfuuyu** [oam-dev/terraform-controller#302]
https://github.com/oam-dev/terraform-controller/blob/master/chart/templates/terraform_controller.yaml#L38

```yaml
{ { if .Values.jobNodeSelector } }
- name: JOB_NODE_SELECTOR
  value: { { .Values.jobNodeSelector } }
{ { end } }
```
should be

```yaml
{{ if .Values.jobNodeSelector }}
- name: JOB_NODE_SELECTOR
  value: {{ .Values.jobNodeSelector }}
{{ end }}
```
