### ISSUE TITLE
Hashicorp AWS provider download runs into permission denied after upgrade from v0.1.12 -> v0.1.13

### ISSUE THREAD

**Issue by neinkeinkaffee** [oam-dev/terraform-controller#72]
After upgrading to v0.1.13 today, components that were getting applied fine with v0.1.12 run into a permission denied issue.
Not 100% sure if this has to do with any of the changes that happened between the two releases (e.g. the switch of the docker-terraform image)?

The logs of the terraform-apply pod look are the following:
```
localstack $ kubectl logs first-input-port-apply-g7mjv
Initializing the backend...
Initializing provider plugins...
- Reusing previous version of hashicorp/aws from the dependency lock file
- Using previously-installed hashicorp/aws v3.36.0
Terraform has been successfully initialized!
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
╷
│ Error: Could not load plugin
│
│
│ Plugin reinitialization required. Please run "terraform init".
│
│ Plugins are external binaries that Terraform uses to access and manipulate
│ resources. The configuration provided requires plugins which can't be
│ located,
│ don't satisfy the version constraints, or are otherwise incompatible.
│
│ Terraform automatically discovers provider requirements from your
│ configuration, including providers used in child modules. To see the
│ requirements and constraints, run "terraform providers".
│
│ failed to instantiate provider "registry.terraform.io/hashicorp/aws" to
│ obtain schema: fork/exec
│ .terraform/providers/registry.terraform.io/hashicorp/aws/3.36.0/linux_amd64/terraform-provider-aws_v3.36.0_x5:
│ permission denied
```

The components failing are ones like this simplistic toy component:
```
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: s3-test
  annotations:
    definition.oam.dev/description: Terraform configuration for s3 input port
    type: terraform
spec:
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
  schematic:
    terraform:
      configuration: |
        resource "aws_s3_bucket" "bucket-acl" {
          bucket = "hardcodedfoo123"
          acl    = "private"
        }
```

And, just for completeness, the corresponding application template:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: some-application
spec:
  components:
    - name: first-input-port
      type: s3-test
      properties:
        writeConnectionSecretToRef:
          name: first-input-port-connection
          namespace: default
```

And the provider, more or less a 1:1 copy from the one in the getting-started docs:
```
apiVersion: terraform.core.oam.dev/v1beta1
kind: Provider
metadata:
  name: default
spec:
  provider: aws
  region: us-east-1
  credentials:
    source: Secret
    secretRef:
      namespace: vela-system
      name: aws-account-creds
      key: credentials
```
